config/routes.rb
Rails.application.routes.draw do

  root 'main#index'

  #регистрация
  get '/signup',        to: 'users#new'
  #вход
  get '/signin',        to: 'sessions#new'
  #выход
  delete '/signout',    to: 'sessions#destroy'

  resources :users
  resources :tests

  #назначить курс
  get '/assign',        to: 'tests#index'
  post '/tests',        to: 'tests#create_dop_info'

  #что назначено
  get '/check',         to: 'users#index'

  post '/tests/:id',    to: 'tests#question'

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord

  has_and_belongs_to_many :tests

  before_save :create_email
  before_create :create_remember_token

  ########валидация при регистрации########

  validates_presence_of :user_name, :surname, :email, message: 'Заполните поле'
  validates_length_of :user_name, :surname, minimum: 3, message: 'Минимальная длина 3 символа'
  validates_format_of :user_name, :surname, with: /[\u0410-\u044F]+/i, message: 'пишите русскими буквами'
  validates_format_of :email, with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: 'неккоректный формат'

  #проверка уникальности email в базе с учетом регистра
  validates_uniqueness_of :email, case_sensitive: false

  validates_length_of :password, minimum: 6, message: 'Минимальная длина 6 символов'

  #создание виртуальных полей и проверка на наличие и совпадения password и password_confirmation
  # + шифрует для записи в базу User.password_digest с использованием gem 'bcrypt'
  has_secure_password

  private

  #пишем в базу User.remember_token
  def create_remember_token
    #Digest - библиотека, SHA1 - алгоритм хеширования, hexdigest - метод
    #SecureRandom - модуль, urlsafe_base64 - метод возвращает случайную строку длиной в 16 символов
    #SecureRandom.urlsafe_base64 - это сам токен из случайных 16 символов
    #Digest::SHA1.hexdigest - шифруем токен
    self.remember_token = Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64)
  end

  #сохраняем в базу поле User.email в нижнем регистре
  def create_email
    self.email = email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

    #назначено
    @user_tests_active = User_Test.where(user_id: current_user.id, status_id: 1)

    @mass_active = []

    @user_tests_active.each do |active|
      @test = Test.find_by(id: active.test_id)
      @mass_active.push(@test)
    end

    #пройдены
    @user_tests_passed = User_Test.where(user_id: current_user.id, status_id: 2)

    @mass_passed = []

    @user_tests_passed.each do |passed|
      @test = Test.find_by(id: passed.test_id)
      @mass_passed.push(@test)
    end

  end

  def new
    @user = User.new
  end

  def show

  end

  def create

      @user = User.new(user_params)
      if @user.save
        flash[:success] = 'Вы зарегистрировались!'
        sign_in(@user)
        redirect_to root_path
      else
        flash[:error] = 'Что то пошло не так!'
        render 'new'
      end

  end


  private

  def user_params
    params.require(:user).permit(:user_name, :surname, :email, :password, :password_confirmation)
  end


end

app/views/users/index.html.slim
- @title = 'Пройти тест'

.header-h1 Пройти тест

h3 Вам назначены тесты

- if @mass_active.blank?
  p = 'Вам еще не назначили тесты'

- else

  table.table.table-striped
    - @mass_active.each do |active|
      tr
        td = active.test_name
        td = link_to 'Пройти тест', test_path(active.id)

h3 Тесты, которые Вы уже прошли

- if @mass_passed.blank?
  p = 'Вы еще не прошли ни одного теста'

- else

  table.table.table-striped
    - @mass_passed.each do |passed|
      tr
        td = passed.test_name
        td = link_to 'Посмотреть результат', root_path

app/views/users/new.html.slim
- @title = 'Страница регистрации'

.header-h1 Регистрация пользователя
p
  = form_for @user do |f|
    - if @user.errors.any?
      #error_explanation
        h2 = 'Обратите внимания на следующие поля:'
        ul
          - @user.errors.full_messages.each do |message|
            li = message
    .form-inline
      .form-user
        = f.text_field :user_name, required: true, placeholder: 'Имя*', minlength: 3, value: "#{@user.user_name}"
      .form-user
        = f.text_field :surname, required: true, placeholder: 'Фамилия*', minlength: 3, value: "#{@user.surname}"
      .form-user
        = f.text_field :email, required: true, placeholder: 'Электронная почта*', minlength: 5, value: "#{@user.email}"
      .form-user
        = f.password_field :password, required: true, placeholder: 'Пароль*', minlength: 6
      .form-user
        = f.password_field :password_confirmation, required: true, placeholder: 'Подтвердите пароль*', minlength: 6
      .form-rega-btn
        = f.submit('ЗАРЕГИСТРИРОВАТЬСЯ')